### ISSUE TITLE
Importing to Mastodon is inconvenient with the yaseen_hug emojis

### ISSUE THREAD

**Issue by Joshix-1** [SymTrkl/emoji#1]
for mastodon a tar.gz file is better. And I would remove the _256 suffix.

The following file can be easily imported with
[hug_yaseen_1.0.tar.gz](https://github.com/SymTrkl/emoji/files/14764060/hug_yaseen_1.0.tar.gz)

```sh
RAILS_ENV=production bin/tootctl emoji import --category hug_yaseen <path>/hug_yaseen_1.0.tar.gz 
```

**Comment by SymTrkl** [comment]
I just made a zip for the convenience of Akkoma admins, since I've heard that the "import emoji from remote instance" functionality is broken, I hadn't considered setting it up for direct import. Thanks for including the tar.gz, I'm not super familiar with how Masto expects the file to be structured. I'll add it to the release page.
